server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    enableSelfPreservation: false

---

spring:
  profiles: container

server:
  port: 8761

eureka:
  instance:
    prefer-ip-address: true
    hostname: ${EUREKA_HOSTNAME}
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    enableSelfPreservation: false
